# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.runs/synth_1/system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.cache/wt [current_project]
set_property parent.project_path C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Uni/Labor-SoC-Design/zedboard_aes-master/ip_repo/AES_PROCESS_1.0
  c:/Uni/Labor-SoC-Design/zedboard_aes-master/ip_repo/pwr_mon_1.0
  c:/Uni/Labor-SoC-Design/zedboard_aes-master/ip_repo/AMA142_OLED
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_AMA142_OLED_AXI_0/src/charLib/charLib.coe
read_vhdl -library xil_defaultlib C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/imports/src/system_wrapper.vhd
add_files C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/const.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_axi_gpio_1_1/system_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_axi_gpio_1_1/system_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_pwr_mon_0_0/src/system_axi_gpio_1_1/system_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_AMA142_OLED_AXI_0/src/charLib/charLib_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_BTN_GPIO_AXI_0/system_BTN_GPIO_AXI_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_BTN_GPIO_AXI_0/system_BTN_GPIO_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_BTN_GPIO_AXI_0/system_BTN_GPIO_AXI_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_SW_LED_GPIO_AXI_0/system_SW_LED_GPIO_AXI_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_SW_LED_GPIO_AXI_0/system_SW_LED_GPIO_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_SW_LED_GPIO_AXI_0/system_SW_LED_GPIO_AXI_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/sources_1/bd/system/system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/constrs_1/imports/src/system.xdc
set_property used_in_implementation false [get_files C:/Uni/Labor-SoC-Design/zedboard_aes-master/power_monitor_aes.srcs/constrs_1/imports/src/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_wrapper -part xc7z020clg484-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
